### ISSUE TITLE
BSOD windows XP SP3

### ISSUE THREAD

**Issue by jholgui** [conix-security/zer0m0n#7]
Hello,

I have a Windows XP SP3 (Spanish language). When i execute the analysis with kernel_analysis=yes the virtual machine shows a BSOD. I use cuckoo 1.1 and last github release of zer0m0n. 

Where i can see more information to debug the problem? 

Thank you!

**Comment by angelkillah** [comment]
try with the last version of zer0m0n : https://github.com/zer0box/zer0m0n
and let me know if you still have problems
