### ISSUE TITLE
Cuckoo 1.2 compatability

### ISSUE THREAD

**Issue by lehuff** [conix-security/zer0m0n#9]
Attempting to install on Cuckoo v 1.2 generates a lot of errors from the patch file. It does add kernelland to the web interface but the vm spits an error out about 'get_options' when trying to run the analyzer.

'Analysis failed: Analyzer instance has no attribute 'get_options'

**Comment by zer0box** [comment]
https://github.com/zer0box/zer0m0n (:

**Comment by angelkillah** [comment]
https://github.com/zer0box/zer0m0n 

enjoy (:

**Comment by lehuff** [comment]
Thanks!
